language: node_js
dist: trusty
node_js: 8.9

install:
  - gem install awesome_bot

before_script:
  - yarn install

script:
  - yarn run lint
  - awesome_bot index.html --allow-dupe --allow-redirect --skip-save-results

notifications:
  email:
    on_success: never
